name: backend
services:
  api: 
    build: api
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=psql
      - DB_NAME=app
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 8081:8080
  
  db:
    build: db
    environment:
      - POSTGRES_PASSWORD=psql